local AddItem = Ambi.Inv.AddItem

local function GiveWeapon( ePly, sClass )
    if ePly:HasWeapon( sClass ) then return false end

    ePly:Give( sClass, true )
    ePly:ChatSend( '~G~ [Inv] ~W~ Вы взяли ~G~ '..sClass )

    return true
end

local function GivePermaWeapon( ePly, sClass )
    if ePly:HasWeapon( sClass ) then ePly:ChatPrint( 'У вас уже есть оружие на руках!' ) return false end
    if timer.Exists( 'PermaWeaponBlock:'..ePly:SteamID() ) then ePly:ChatPrint( 'Подождите!' ) return false end

    ePly:Give( sClass, true )
    ePly:GetWeapon( sClass ).cannot_drop = true
    ePly:ChatSend( '~G~ [Inv] ~W~ Вы взяли ~AMBI_PURPLE~ Perma ~W~ оружие ~G~ '..sClass )

    timer.Create( 'PermaWeaponBlock:'..ePly:SteamID(), 60 * 3, 1, function() end )

    return false -- не нужно тратится
end

local CATEGORY = 'Оружие'
local SPEC_STACK = 10

local function AddItemWeapon( sClass, sName, sDesc, sIcon )
    AddItem( 'wep_'..sClass, sName, SPEC_STACK, CATEGORY, DESC, sIcon, function( ePly )
        return GiveWeapon( ePly, sClass )
    end )
end

local function AddItemPermaWeapon( sClass, sName, sDesc, sIcon )
    AddItem( 'wep_perma_'..sClass, sName, SPEC_STACK, CATEGORY, DESC, sIcon, function( ePly )
        return GivePermaWeapon( ePly, sClass )
    end )
end

-- ======================================================================================================
AddItemWeapon( 'arccw_bw3_tommy', 'El. Billy', 'Оружие', 'models/bw3/weapons/c_tommy.mdl' )
AddItemWeapon( 'arccw_melee_knife', 'Knife', 'Оружие', 'models/weapons/w_knife_t.mdl' )
AddItemWeapon( 'arccw_db', 'DB', 'Оружие', 'models/weapons/arccw/w_db.mdl' )
AddItemWeapon( 'arccw_nade_flare', 'Insertion Flare', 'Оружие', 'models/weapons/arccw/w_flare.mdl' )
AddItemWeapon( 'arccw_deagle357', 'Desert Eagle .357', 'Оружие', 'models/weapons/w_pist_deagle.mdl' )
AddItemWeapon( 'arccw_mac11', 'MAC-11', 'Оружие', 'models/weapons/arccw/w_mk201.mdl' )
AddItemWeapon( 'arccw_galil556', 'Galil ARM', 'Оружие', 'models/weapons/arccw/w_lior556.mdl' )
AddItemWeapon( 'arccw_ruger', 'Mk. 2', 'Оружие', 'models/weapons/arccw/w_ruger.mdl' )
AddItemWeapon( 'arccw_nade_smoke', 'Smoke Grenade', 'Оружие', 'models/weapons/w_eq_smokegrenade.mdl' )
AddItemWeapon( 'arccw_ragingbull', 'Raging Bull', 'Оружие', 'models/weapons/arccw/w_ragingbull.mdl' )
AddItemWeapon( 'arccw_usp', 'USP-40', 'Оружие', 'models/weapons/w_pist_usp.mdl' )
AddItemWeapon( 'arccw_g18', 'G18', 'Оружие', 'models/weapons/w_pist_glock18.mdl' )
AddItemWeapon( 'arccw_sg550', 'SG550-1', 'Оружие', 'models/weapons/arccw/w_sg550.mdl' )
AddItemWeapon( 'arccw_sg552', 'SG552', 'Оружие', 'models/weapons/arccw/w_roland.mdl' )
AddItemWeapon( 'arccw_fiveseven', 'Five-seveN', 'Оружие', 'models/weapons/w_pist_fiveseven.mdl' )
AddItemWeapon( 'arccw_shorty', 'M3 Super 90', 'Оружие', 'models/weapons/arccw/w_defender.mdl' )
AddItemWeapon( 'arccw_augpara', 'AUG Para', 'Оружие', 'models/weapons/arccw/w_para9.mdl' )
AddItemWeapon( 'arccw_rpg7', 'RPG-7', 'Оружие', 'models/weapons/arccw/w_rpg7.mdl' )
AddItemWeapon( 'arccw_base', 'ArcCW Base', 'Оружие', '' )
AddItemWeapon( 'arccw_m72law', 'M72 LAW', 'Оружие', 'models/weapons/arccw/w_rpg7.mdl' )
AddItemWeapon( 'arccw_scout', 'Scout', 'Оружие', 'models/weapons/arccw/w_psrs.mdl' )
AddItemWeapon( 'arccw_ak47', 'AK-47', 'Оружие', 'models/weapons/arccw/w_type2.mdl' )
AddItemWeapon( 'arccw_gauss_rifle', 'M2014 Gauss Rifle', 'Оружие', 'models/weapons/arccw/w_gauss_rifle.mdl' )
AddItemWeapon( 'arccw_aug', 'AUG A2', 'Оружие', 'models/weapons/arccw/w_para.mdl' )
AddItemWeapon( 'arccw_nade_semtex', 'Semtex', 'Оружие', 'models/weapons/arccw/w_nade_semtex.mdl' )
AddItemWeapon( 'arccw_ump45', 'UMP-45', 'Оружие', 'models/weapons/arccw/w_mps2.mdl' )
AddItemWeapon( 'arccw_welrod', 'Welrod', 'Оружие', 'models/weapons/arccw/w_welrod.mdl' )
AddItemWeapon( 'arccw_m14', 'M14', 'Оружие', 'models/weapons/arccw/w_m14.mdl' )
AddItemWeapon( 'arccw_m9', 'M92FS', 'Оружие', 'models/weapons/w_pist_elite_single.mdl' )
AddItemWeapon( 'arccw_melee_fists', 'Fists', 'Оружие', '' )
AddItemWeapon( 'arccw_tmp', 'MP9', 'Оружие', 'models/weapons/arccw/w_tmp.mdl' )
AddItemWeapon( 'arccw_minigun', 'M134', 'Оружие', 'models/weapons/arccw/w_minigun.mdl' )
AddItemWeapon( 'arccw_m107', 'M107', 'Оружие', 'models/weapons/arccw/w_bfg.mdl' )
AddItemWeapon( 'arccw_m1014', 'M1014', 'Оружие', 'models/weapons/arccw/w_as1217.mdl' )
AddItemWeapon( 'arccw_p90', 'P90', 'Оружие', 'models/weapons/arccw/w_pdw57.mdl' )
AddItemWeapon( 'arccw_jesusword', 'Jesus sword', 'Оружие', 'models/weapons/darky_m/w_jesusword.mdl' )
AddItemWeapon( 'arccw_deagle50', 'Desert Eagle .50', 'Оружие', 'models/weapons/arccw/w_gce.mdl' )
AddItemWeapon( 'arccw_nade_incendiary', 'Thermite Grenade', 'Оружие', 'models/weapons/arccw/w_nade_incendiary.mdl' )
AddItemWeapon( 'arccw_saiga', 'Saiga-12', 'Оружие', 'models/weapons/arccw/w_saiga.mdl' )
AddItemWeapon( 'arccw_bizon', 'PP-19-02 Bizon', 'Оружие', 'models/weapons/arccw/w_bizon.mdl' )
AddItemWeapon( 'arccw_makarov', 'Makarov', 'Оружие', 'models/weapons/arccw/w_pmt.mdl' )
AddItemWeapon( 'arccw_db_sawnoff', 'Sawn-Off', 'Оружие', 'models/weapons/arccw/w_sawnoff.mdl' )
AddItemWeapon( 'arccw_g3a3', 'G3A3', 'Оружие', 'models/weapons/arccw/w_ag63.mdl' )
AddItemWeapon( 'arccw_nade_frag', 'Frag Grenade', 'Оружие', 'models/weapons/arccw/w_nade_frag.mdl' )
AddItemWeapon( 'arccw_nade_claymore', 'Claymore', 'Оружие', 'models/weapons/arccw/w_nade_claymore.mdl' )
AddItemWeapon( 'arccw_m4a1', 'M4A1', 'Оружие', 'models/weapons/arccw/mk4.mdl' )
AddItemWeapon( 'arccw_nade_impact', 'Impact Grenade', 'Оружие', 'models/weapons/arccw/w_nade_impact.mdl' )
AddItemWeapon( 'arccw_m60', 'M60', 'Оружие', 'models/weapons/arccw/w_m60.mdl' )
AddItemWeapon( 'arccw_contender', 'G2 Contender', 'Оружие', 'models/weapons/arccw/w_contender.mdl' )
AddItemWeapon( 'arccw_famas', 'FAMAS', 'Оружие', 'models/weapons/arccw/w_canin.mdl' )
AddItemWeapon( 'arccw_minimi', 'Minimi Para', 'Оружие', 'models/weapons/arccw/w_m2000g.mdl' )
AddItemWeapon( 'arccw_nade_flash', 'Flashbang', 'Оружие', 'models/weapons/w_eq_flashbang.mdl' )
AddItemWeapon( 'arccw_awm', 'AWM', 'Оружие', 'models/weapons/arccw/w_hs338.mdl' )
AddItemWeapon( 'arccw_nade_gas', 'Gas Grenade', 'Оружие', 'models/weapons/arccw/w_nade_gas.mdl' )
AddItemWeapon( 'arccw_p228', 'P228', 'Оружие', 'models/weapons/w_pist_p228.mdl' )
AddItemWeapon( 'arccw_ump9', 'UMP-9', 'Оружие', 'models/weapons/arccw/w_mpk1.mdl' )
AddItemWeapon( 'arccw_mp5', 'MP5A3', 'Оружие', 'models/weapons/arccw/w_mp5.mdl' )

-- ======================================================================================================
AddItemPermaWeapon( 'arccw_bw3_tommy', '[Perma] El. Billy', 'Оружие', 'models/bw3/weapons/c_tommy.mdl' )
AddItemPermaWeapon( 'arccw_melee_knife', '[Perma] Knife', 'Оружие', 'models/weapons/w_knife_t.mdl' )
AddItemPermaWeapon( 'arccw_db', '[Perma] DB', 'Оружие', 'models/weapons/arccw/w_db.mdl' )
AddItemPermaWeapon( 'arccw_nade_flare', '[Perma] Insertion Flare', 'Оружие', 'models/weapons/arccw/w_flare.mdl' )
AddItemPermaWeapon( 'arccw_deagle357', '[Perma] Desert Eagle .357', 'Оружие', 'models/weapons/w_pist_deagle.mdl' )
AddItemPermaWeapon( 'arccw_mac11', '[Perma] MAC-11', 'Оружие', 'models/weapons/arccw/w_mk201.mdl' )
AddItemPermaWeapon( 'arccw_galil556', '[Perma] Galil ARM', 'Оружие', 'models/weapons/arccw/w_lior556.mdl' )
AddItemPermaWeapon( 'arccw_ruger', '[Perma] Mk. 2', 'Оружие', 'models/weapons/arccw/w_ruger.mdl' )
AddItemPermaWeapon( 'arccw_nade_smoke', '[Perma] Smoke Grenade', 'Оружие', 'models/weapons/w_eq_smokegrenade.mdl' )
AddItemPermaWeapon( 'arccw_ragingbull', '[Perma] Raging Bull', 'Оружие', 'models/weapons/arccw/w_ragingbull.mdl' )
AddItemPermaWeapon( 'arccw_usp', '[Perma] USP-40', 'Оружие', 'models/weapons/w_pist_usp.mdl' )
AddItemPermaWeapon( 'arccw_g18', '[Perma] G18', 'Оружие', 'models/weapons/w_pist_glock18.mdl' )
AddItemPermaWeapon( 'arccw_sg550', '[Perma] SG550-1', 'Оружие', 'models/weapons/arccw/w_sg550.mdl' )
AddItemPermaWeapon( 'arccw_sg552', '[Perma] SG552', 'Оружие', 'models/weapons/arccw/w_roland.mdl' )
AddItemPermaWeapon( 'arccw_fiveseven', '[Perma] Five-seveN', 'Оружие', 'models/weapons/w_pist_fiveseven.mdl' )
AddItemPermaWeapon( 'arccw_shorty', '[Perma] M3 Super 90', 'Оружие', 'models/weapons/arccw/w_defender.mdl' )
AddItemPermaWeapon( 'arccw_augpara', '[Perma] AUG Para', 'Оружие', 'models/weapons/arccw/w_para9.mdl' )
AddItemPermaWeapon( 'arccw_rpg7', '[Perma] RPG-7', 'Оружие', 'models/weapons/arccw/w_rpg7.mdl' )
AddItemPermaWeapon( 'arccw_m72law', '[Perma] M72 LAW', 'Оружие', 'models/weapons/arccw/w_rpg7.mdl' )
AddItemPermaWeapon( 'arccw_scout', '[Perma] Scout', 'Оружие', 'models/weapons/arccw/w_psrs.mdl' )
AddItemPermaWeapon( 'arccw_ak47', '[Perma] AK-47', 'Оружие', 'models/weapons/arccw/w_type2.mdl' )
AddItemPermaWeapon( 'arccw_gauss_rifle', '[Perma] M2014 Gauss Rifle', 'Оружие', 'models/weapons/arccw/w_gauss_rifle.mdl' )
AddItemPermaWeapon( 'arccw_aug', '[Perma] AUG A2', 'Оружие', 'models/weapons/arccw/w_para.mdl' )
AddItemPermaWeapon( 'arccw_nade_semtex', '[Perma] Semtex', 'Оружие', 'models/weapons/arccw/w_nade_semtex.mdl' )
AddItemPermaWeapon( 'arccw_ump45', '[Perma] UMP-45', 'Оружие', 'models/weapons/arccw/w_mps2.mdl' )
AddItemPermaWeapon( 'arccw_welrod', '[Perma] Welrod', 'Оружие', 'models/weapons/arccw/w_welrod.mdl' )
AddItemPermaWeapon( 'arccw_m14', '[Perma] M14', 'Оружие', 'models/weapons/arccw/w_m14.mdl' )
AddItemPermaWeapon( 'arccw_m9', '[Perma] M92FS', 'Оружие', 'models/weapons/w_pist_elite_single.mdl' )
AddItemPermaWeapon( 'arccw_melee_fists', '[Perma] Fists', 'Оружие', '' )
AddItemPermaWeapon( 'arccw_tmp', '[Perma] MP9', 'Оружие', 'models/weapons/arccw/w_tmp.mdl' )
AddItemPermaWeapon( 'arccw_minigun', '[Perma] M134', 'Оружие', 'models/weapons/arccw/w_minigun.mdl' )
AddItemPermaWeapon( 'arccw_m107', '[Perma] M107', 'Оружие', 'models/weapons/arccw/w_bfg.mdl' )
AddItemPermaWeapon( 'arccw_m1014', '[Perma] M1014', 'Оружие', 'models/weapons/arccw/w_as1217.mdl' )
AddItemPermaWeapon( 'arccw_p90', '[Perma] P90', 'Оружие', 'models/weapons/arccw/w_pdw57.mdl' )
AddItemPermaWeapon( 'arccw_jesusword', '[Perma] Jesus sword', 'Оружие', 'models/weapons/darky_m/w_jesusword.mdl' )
AddItemPermaWeapon( 'arccw_deagle50', '[Perma] Desert Eagle .50', 'Оружие', 'models/weapons/arccw/w_gce.mdl' )
AddItemPermaWeapon( 'arccw_nade_incendiary', '[Perma] Thermite Grenade', 'Оружие', 'models/weapons/arccw/w_nade_incendiary.mdl' )
AddItemPermaWeapon( 'arccw_saiga', '[Perma] Saiga-12', 'Оружие', 'models/weapons/arccw/w_saiga.mdl' )
AddItemPermaWeapon( 'arccw_bizon', '[Perma] PP-19-02 Bizon', 'Оружие', 'models/weapons/arccw/w_bizon.mdl' )
AddItemPermaWeapon( 'arccw_makarov', '[Perma] Makarov', 'Оружие', 'models/weapons/arccw/w_pmt.mdl' )
AddItemPermaWeapon( 'arccw_db_sawnoff', '[Perma] Sawn-Off', 'Оружие', 'models/weapons/arccw/w_sawnoff.mdl' )
AddItemPermaWeapon( 'arccw_g3a3', '[Perma] G3A3', 'Оружие', 'models/weapons/arccw/w_ag63.mdl' )
AddItemPermaWeapon( 'arccw_nade_frag', '[Perma] Frag Grenade', 'Оружие', 'models/weapons/arccw/w_nade_frag.mdl' )
AddItemPermaWeapon( 'arccw_nade_claymore', '[Perma] Claymore', 'Оружие', 'models/weapons/arccw/w_nade_claymore.mdl' )
AddItemPermaWeapon( 'arccw_m4a1', '[Perma] M4A1', 'Оружие', 'models/weapons/arccw/mk4.mdl' )
AddItemPermaWeapon( 'arccw_nade_impact', '[Perma] Impact Grenade', 'Оружие', 'models/weapons/arccw/w_nade_impact.mdl' )
AddItemPermaWeapon( 'arccw_m60', '[Perma] M60', 'Оружие', 'models/weapons/arccw/w_m60.mdl' )
AddItemPermaWeapon( 'arccw_contender', '[Perma] G2 Contender', 'Оружие', 'models/weapons/arccw/w_contender.mdl' )
AddItemPermaWeapon( 'arccw_famas', '[Perma] FAMAS', 'Оружие', 'models/weapons/arccw/w_canin.mdl' )
AddItemPermaWeapon( 'arccw_minimi', '[Perma] Minimi Para', 'Оружие', 'models/weapons/arccw/w_m2000g.mdl' )
AddItemPermaWeapon( 'arccw_nade_flash', '[Perma] Flashbang', 'Оружие', 'models/weapons/w_eq_flashbang.mdl' )
AddItemPermaWeapon( 'arccw_awm', '[Perma] AWM', 'Оружие', 'models/weapons/arccw/w_hs338.mdl' )
AddItemPermaWeapon( 'arccw_nade_gas', '[Perma] Gas Grenade', 'Оружие', 'models/weapons/arccw/w_nade_gas.mdl' )
AddItemPermaWeapon( 'arccw_p228', '[Perma] P228', 'Оружие', 'models/weapons/w_pist_p228.mdl' )
AddItemPermaWeapon( 'arccw_ump9', '[Perma] UMP-9', 'Оружие', 'models/weapons/arccw/w_mpk1.mdl' )
AddItemPermaWeapon( 'arccw_mp5', '[Perma] MP5A3', 'Оружие', 'models/weapons/arccw/w_mp5.mdl' )