-- Полная информация по созданию работ --> https://titanovskyteam.gitbook.io/darkrp/getting-started/create-jobs

if not Ambi.DarkRP then return end

local C = Ambi.Packages.Out( 'colors' )
local Add = Ambi.DarkRP.AddJob
local SimpleAddJob = Ambi.DarkRP.SimpleAddJob

local SPAWN_FOREST = {
    { pos = Vector( 1436, -13860, -151 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( 2933, -13533, -139 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( 4843, -14139, 22 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( 5862, -13030, -61 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( 5929, -11442, -151 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( 1642, -11785, -117 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( -1422, -10248, -191 ), ang = Angle( 0, 90, 0 ) },
}

local SPAWN_UNDERGROUND = {
    { pos = Vector( -2073, 849, -900 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( -2056, 530, -896 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( -2075, 20, -896 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( -2067, -561, -896 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( -2063, -1211, -889 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( -1566, -1783, -426 ), ang = Angle( 0, 0, 0 ) },
    { pos = Vector( -1899, -1787, -428 ), ang = Angle( 0, 0, 0 ) },
    { pos = Vector( -2149, -1787, -434 ), ang = Angle( 0, 0, 0 ) },
    { pos = Vector( -2182, -1973, -422 ), ang = Angle( 0, 0, 0 ) },
}

local SPAWN_FOREST_AND_UNDERGROUND = {
    { pos = Vector( 1436, -13860, -151 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( 2933, -13533, -139 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( 4843, -14139, 22 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( 5862, -13030, -61 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( 5929, -11442, -151 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( 1642, -11785, -117 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( -1422, -10248, -191 ), ang = Angle( 0, 90, 0 ) },

    { pos = Vector( -2073, 849, -900 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( -2056, 530, -896 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( -2075, 20, -896 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( -2067, -561, -896 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( -2063, -1211, -889 ), ang = Angle( 0, 90, 0 ) },
    { pos = Vector( -1566, -1783, -426 ), ang = Angle( 0, 0, 0 ) },
    { pos = Vector( -1899, -1787, -428 ), ang = Angle( 0, 0, 0 ) },
    { pos = Vector( -2149, -1787, -434 ), ang = Angle( 0, 0, 0 ) },
    { pos = Vector( -2182, -1973, -422 ), ang = Angle( 0, 0, 0 ) },
}

-- ----------------------------------------------------------------------------------------------------------------------------
local CATEGORY = 'M | Dark'

Add( 'TEAM_DEMON', { -- Фаерболл 
    dark_mystic = true,
    name = 'Демон', 
    command = 'demon', 
    category = CATEGORY, 
    description = '[ДАННЫЕ УДАЛЕНЫ]', 
    color = C.AMBI_PURPLE, 
    max = 2,
    demote = false,
    --can_join_command = false,
    can_buy_door = false,
    can_arrest = false,
    can_wanted = false,
    can_warrant = false,
    can_pickup_weapons = false,
    can_buy_shop_item = false,
    walkspeed = 240,
    runspeed = 530,
    hp = 2400,
    salary = 0,
    weapons = { 'weapon_fists', 'blood_mace', 'keys' },
    models = { 'models/bloodletter1.mdl' },
    spawns = SPAWN_FOREST_AND_UNDERGROUND,
    level = 2,
} )

Add( 'TEAM_VAMPIRE', { -- Сосание 
    dark_mystic = true,
    name = 'Вампир', 
    command = 'vampire', 
    category = CATEGORY, 
    description = '[ДАННЫЕ УДАЛЕНЫ]', 
    color = C.AMBI_PURPLE, 
    max = 3,
    demote = false,
    --can_join_command = false,
    can_buy_door = false,
    can_arrest = false,
    can_wanted = false,
    can_warrant = false,
    runspeed = 590,
    hp = 300,
    salary = 0,
    weapons = { 'weapon_fists', 'lockpick', 'keys' },
    models = { 'models/player/monstermash/mm_vampire.mdl', 'models/player/monstermash/mm_nosferatu.mdl' },
    spawns = SPAWN_UNDERGROUND,
    level = 3,
} )

Add( 'TEAM_NECROMANCER', { -- Вызывать Молний -- 
    dark_mystic = true,
    name = 'Некромант', 
    command = 'necromancer', 
    category = CATEGORY, 
    description = '[ДАННЫЕ УДАЛЕНЫ]', 
    color = C.AMBI_PURPLE, 
    max = 2,
    demote = false,
    --can_join_command = false,
    can_buy_door = false,
    can_arrest = false,
    can_wanted = false,
    can_warrant = false,
    can_pickup_weapons = false,
    can_buy_shop_item = false,
    walkspeed = 280,
    runspeed = 590,
    hp = 300,
    salary = 0,
    weapons = { 'weapon_fists', 'keys' },
    models = { 'models/player/palpatine/palpatine.mdl' },
    spawns = SPAWN_FOREST_AND_UNDERGROUND,
    level = 3,
} )

Add( 'TEAM_LYCAN', { -- Невидимость (большое кд)
    dark_mystic = true,
    name = 'Оборотень', 
    command = 'lycan', 
    category = CATEGORY, 
    description = '[ДАННЫЕ УДАЛЕНЫ]', 
    color = C.AMBI_PURPLE, 
    max = 2,
    demote = false,
    --can_join_command = false,
    can_buy_door = false,
    can_arrest = false,
    can_wanted = false,
    can_warrant = false,
    can_pickup_weapons = false,
    can_buy_shop_item = false,
    walkspeed = 320,
    runspeed = 540,
    multiply_damage = 3,
    hp = 1800,
    salary = 0,
    weapons = { 'weapon_fists', 'keys' },
    models = { 'models/player/lycanwerewolf/lycanwerewolf.mdl' },
    spawns = SPAWN_FOREST,
    level = 3,
} )

Add( 'TEAM_MURDER', { -- Режим Ярости (время)
    dark_mystic = true,
    name = 'Маньяк', 
    command = 'murder', 
    category = CATEGORY, 
    description = '[ДАННЫЕ УДАЛЕНЫ]', 
    color = C.AMBI_PURPLE, 
    max = 4,
    demote = false,
    --can_join_command = false,
    can_buy_door = false,
    can_arrest = false,
    can_wanted = false,
    can_warrant = false,
    can_pickup_weapons = false,
    can_buy_shop_item = false,
    hp = 2000,
    salary = 0,
    weapons = { 'weapon_fists', 'dagger', 'keys' },
    models = { 'models/player/cheapman_h2o.mdl' },
    spawns = SPAWN_UNDERGROUND,
    level = 2,
} )

-- VIP
Add( 'TEAM_ORACLE', { -- Телепортация 
    is_vip = true,
    dark_mystic = true,
    name = 'Оракул', 
    command = 'oracle', 
    category = CATEGORY, 
    description = '[ДАННЫЕ УДАЛЕНЫ]', 
    color = C.AMBI_PURPLE, 
    max = 2,
    demote = false,
    --can_join_command = false,
    can_arrest = false,
    can_wanted = false,
    can_warrant = false,
    can_buy_door = false,
    can_pickup_weapons = false,
    can_buy_shop_item = false,
    walkspeed = 380,
    runspeed = 690,
    jumppower = 450,
    hp = 1000,
    salary = 0,
    weapons = { 'weapon_fists', 'blink_swep', 'blood_dagger', 'keys' },
    models = { 'models/darksouls/characters/hollow_thief.mdl' },
    spawns = SPAWN_FOREST,
    level = 5,
} )

-- Premium
Add( 'TEAM_PYRAMIDHEAD', { -- ? 
    is_premium = true,
    dark_mystic = true,
    name = 'Пирамида', 
    command = 'pyramidhead', 
    category = CATEGORY, 
    description = '[ДАННЫЕ УДАЛЕНЫ]', 
    color = C.AMBI_PURPLE, 
    max = 2,
    demote = false,
    --can_join_command = false,
    can_buy_door = false,
    can_arrest = false,
    can_wanted = false,
    can_warrant = false,
    can_pickup_weapons = false,
    can_buy_shop_item = false,
    walkspeed = 220,
    runspeed = 340,
    hp = 6666,
    block_user = true,
    salary = 0,
    multiply_damage = 4,
    weapons = { 'weapon_fists', 'spear', 'keys' },
    models = { 'models/player/pyramidhead/pyramidhead.mdl' },
    spawns = SPAWN_UNDERGROUND
} )

Add( 'TEAM_ANUBIS', { -- Бессмертие на время 
    is_premium = true,
    dark_mystic = true,
    name = 'Анубис', 
    command = 'anubis', 
    category = CATEGORY, 
    description = '[ДАННЫЕ УДАЛЕНЫ]', 
    color = C.AMBI_BLOOD, 
    max = 1,
    demote = false,
    --can_join_command = false,
    can_arrest = false,
    can_wanted = false,
    can_warrant = false,
    hp = 2000,
    salary = 0,
    take_multiply_damage = 0.5,
    block_user = true,
    weapons = { 'weapon_fists', 'weapon_blitz_magic', 'weapon_firem', 'keys' },
    models = { 'models/player/captainpawn/anubissmite.mdl' },
    spawns = SPAWN_FOREST,
    level = 6,
} )

Add( 'TEAM_ZOMBIE', { 
    dark_mystic = true,
    name = 'Зомби', 
    command = 'zombie', 
    category = CATEGORY, 
    description = '[ДАННЫЕ УДАЛЕНЫ]', 
    color = C.AMBI_PURPLE, 
    max = 0,
    demote = false,
    can_join_command = false,
    can_buy_door = false,
    can_arrest = false,
    can_wanted = false,
    can_warrant = false,
    can_pickup_weapons = false,
    can_buy_shop_item = false,
    walkspeed = 250,
    runspeed = 420,
    hp = 250,
    salary = 0,
    multiply_damage = 2,
    weapons = { 'weapon_fists', 'keys' },
    models = { 'models/player/horror/horror.mdl', 'models/player/monstermash/mm_zombie.mdl', 'models/player/hidden/hidden.mdl' },
} )

Add( 'TEAM_NURSE', { 
    dark_mystic = true,
    name = 'Мед.сестра', 
    command = 'nurse', 
    category = CATEGORY, 
    description = 'Нападает исключительно на мужчин. В прошлой жизни ее изнасиловал и убил мужчина, теперь она убивает всех мужчин в попытках найти своего убийцу и обрести покой. Говорят, что она отрезает половые органы мужчинам и им же скармливает...', 
    color = C.AMBI_PURPLE, 
    max = 4,
    demote = false,
    can_buy_door = false,
    can_arrest = false,
    can_wanted = false,
    can_warrant = false,
    can_pickup_weapons = false,
    can_buy_shop_item = false,
    walkspeed = 250,
    runspeed = 420,
    hp = 250,
    salary = 0,
    multiply_damage = 3,
    weapons = { 'demonic_dagger', 'keys' },
    models = { 'models/psychedelicum/silent_hill/bubble_nurse/bubble_nurse_pm.mdl' },
    level = 5,
} )

-- Add( 'TEAM_SCARECROW', { 
--     name = 'Пугало', 
--     command = 'scarecrow', 
--     category = CATEGORY, 
--     description = '[ДАННЫЕ УДАЛЕНЫ]', 
--     color = C.AMBI_PURPLE, 
--     max = 2,
--     demote = false,
--     can_join_command = false,
--     can_buy_door = false,
--     can_arrest = false,
--     can_wanted = false,
--     can_warrant = false,
--     can_pickup_weapons = false,
--     can_buy_shop_item = false,
--     take_multiply_damage = 0.4,
--     multiply_damage = 3,
--     hp = 666,
--     salary = 0,
--     weapons = { 'weapon_fists' },
--     models = { 'models/player/monstermash/mm_scarecrow.mdl' },
--     spawns = {
--         { pos = Vector( 3983, 72, -270 ), ang = Angle( 0, -90, 0 )},
--         { pos = Vector( 3626, 94, -270 ), ang = Angle( 0, -90, 0 )},
--         { pos = Vector( 3244, 47, -270 ), ang = Angle( 0, -90, 0 )},
--     }
-- } )

-- Add( 'TEAM_GOBLIN', { 
--     name = 'Гоблин', 
--     command = 'goblin', 
--     category = CATEGORY, 
--     description = '[ДАННЫЕ УДАЛЕНЫ]', 
--     color = C.AMBI_PURPLE, 
--     max = 2,
--     demote = false,
--     can_join_command = false,
--     can_buy_door = false,
--     can_arrest = false,
--     can_wanted = false,
--     can_warrant = false,
--     can_buy_shop_item = false,
--     walkspeed = 280,
--     runspeed = 590,
--     hp = 800,
--     salary = 0,
--     weapons = { 'weapon_fists' },
--     models = { 'models/player/goblin/goblin.mdl' },
--     spawns = {
--         { pos = Vector( 3983, 72, -270 ), ang = Angle( 0, -90, 0 )},
--         { pos = Vector( 3626, 94, -270 ), ang = Angle( 0, -90, 0 )},
--         { pos = Vector( 3244, 47, -270 ), ang = Angle( 0, -90, 0 )},
--     }
-- } )

-- Add( 'TEAM_WORM', { 
--     name = 'Червь', 
--     command = 'worm', 
--     category = CATEGORY, 
--     description = '[ДАННЫЕ УДАЛЕНЫ]', 
--     color = C.AMBI_PURPLE, 
--     max = 2,
--     demote = false,
--     can_join_command = false,
--     can_buy_door = false,
--     can_arrest = false,
--     can_wanted = false,
--     can_warrant = false,
--     can_pickup_weapons = false,
--     can_buy_shop_item = false,
--     walkspeed = 280,
--     runspeed = 490,
--     hp = 666,
--     multiply_damage = 4,
--     salary = 0,
--     weapons = { 'weapon_fists' },
--     models = { 'models/player/verdugo/verdugo.mdl' },
--     spawns = {
--         { pos = Vector( 3983, 72, -270 ), ang = Angle( 0, -90, 0 )},
--         { pos = Vector( 3626, 94, -270 ), ang = Angle( 0, -90, 0 )},
--         { pos = Vector( 3244, 47, -270 ), ang = Angle( 0, -90, 0 )},
--     }
-- } )

-- Add( 'TEAM_BIOSOLDIER', { 
--     name = 'Био-Солдат', 
--     command = 'biosoldier', 
--     category = CATEGORY, 
--     description = '[ДАННЫЕ УДАЛЕНЫ]', 
--     color = C.AMBI_PURPLE, 
--     max = 2,
--     demote = false,
--     can_join_command = false,
--     can_buy_door = false,
--     can_arrest = false,
--     can_wanted = false,
--     can_warrant = false,
--     can_buy_shop_item = false,
--     walkspeed = 280,
--     runspeed = 590,
--     take_multiply_damage = 2,
--     hp = 1000,
--     salary = 0,
--     weapons = { 'weapon_fists', 'weapon_crossbow', 'weapon_shotgun' },
--     models = { 'models/player/jrpc/jin.mdl' },
--     spawns = {
--         { pos = Vector( 3983, 72, -270 ), ang = Angle( 0, -90, 0 )},
--         { pos = Vector( 3626, 94, -270 ), ang = Angle( 0, -90, 0 )},
--         { pos = Vector( 3244, 47, -270 ), ang = Angle( 0, -90, 0 )},
--     }
-- } )

-- Add( 'TEAM_ILLUMINATI', { 
--     name = 'Иллюминат [VIP]', 
--     command = 'illuminati', 
--     category = CATEGORY, 
--     description = '[ДАННЫЕ УДАЛЕНЫ]', 
--     color = C.AMBI_PURPLE, 
--     max = 2,
--     demote = false,
--     can_join_command = false,
--     can_arrest = false,
--     can_wanted = false,
--     can_warrant = false,
--     hp = 300,
--     salary = 0,
--     take_multiply_damage = 0.6,
--     block_user = true,
--     weapons = { 'weapon_fists', 'arccw_gauss_rifle' },
--     models = { 'models/player/monstermash/mm_mad_scientist.mdl' },
--     spawns = {
--         { pos = Vector( 3983, 72, -270 ), ang = Angle( 0, -90, 0 )},
--         { pos = Vector( 3626, 94, -270 ), ang = Angle( 0, -90, 0 )},
--         { pos = Vector( 3244, 47, -270 ), ang = Angle( 0, -90, 0 )},
--     }
-- } )

-- Add( 'TEAM_CAMHEAD', { 
--     name = 'Камера-Головый [VIP]', 
--     command = 'camhead', 
--     vip = true,
--     category = CATEGORY, 
--     description = '[ДАННЫЕ УДАЛЕНЫ]', 
--     color = C.AMBI_BLOOD, 
--     max = 1,
--     demote = false,
--     can_join_command = false,
--     can_arrest = false,
--     can_wanted = false,
--     can_warrant = false,
--     hp = 500,
--     salary = 0,
--     block_user = true,
--     weapons = { 'weapon_fists' },
--     models = { 'models/bala/cam_head_pm.mdl' },
--     spawns = {
--         { pos = Vector( 3983, 72, -270 ), ang = Angle( 0, -90, 0 )},
--         { pos = Vector( 3626, 94, -270 ), ang = Angle( 0, -90, 0 )},
--         { pos = Vector( 3244, 47, -270 ), ang = Angle( 0, -90, 0 )},
--     }
-- } )

-- Add( 'TEAM_TVMAN', { 
--     name = 'Ходячее TV [VIP]', 
--     command = 'tvman', 
--     vip = true,
--     category = CATEGORY, 
--     description = '[ДАННЫЕ УДАЛЕНЫ]', 
--     color = C.AMBI_BLOOD, 
--     max = 1,
--     demote = false,
--     can_join_command = false,
--     can_arrest = false,
--     can_wanted = false,
--     can_warrant = false,
--     hp = 500,
--     salary = 0,
--     block_user = true,
--     weapons = { 'weapon_fists' },
--     models = { 'models/player/jellikpm.mdl' },
--     spawns = {
--         { pos = Vector( 3983, 72, -270 ), ang = Angle( 0, -90, 0 )},
--         { pos = Vector( 3626, 94, -270 ), ang = Angle( 0, -90, 0 )},
--         { pos = Vector( 3244, 47, -270 ), ang = Angle( 0, -90, 0 )},
--     }
-- } )