MT_IGSItem.End = function() end

-- ------------------------------------------------------------------------------------------------------
local CATEGORY = 'Поддержка'

IGS( 'Основатель', 'addon1' )
	:SetPrice( 8000 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( '• Получаете фулл сборку и доступ к серверу \n• Безграничное правление над проектом' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Спасибо!' )
	end )
:End()

-- ------------------------------------------------------------------------------------------------------
local CATEGORY = 'Привилегия'

IGS( 'VIP [30 Дней]', 'priv1' )
	:SetPrice( 99 )
	:SetTerm( 30 )
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetDescription( 'Привилегия\nБольше оружия в /kit weapons\nx2 Зарплата и опыт\nДоступны новые профессии\nДоступен специальный Маник\nДоступны новые Способности' )
	:SetOnActivate( function( ePly )
		ePly:SetPrivilege( 'vip', 30 )
		ePly:ChatSend( '~AMBI~ • ~W~ Вы получили VIP на 30 дней' )
	end )
:End()

IGS( 'VIP [Навсегда]', 'priv1_forever' )
	:SetPrice( 199 )
	:SetPerma()
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetDescription( 'Привилегия\nВсе оружия в /kit weapons\nx2 Зарплата и опыт\nДоступны новые профессии\nДоступен специальный Маник\nДоступны новые Способности' )
	:SetOnActivate( function( ePly )
		ePly:SetPrivilege( 'vip', 999999 )
		ePly:ChatSend( '~AMBI~ • ~W~ Вы получили VIP навсегда!' )
	end )
:End()

IGS( 'Premium [30 Дней]', 'priv2' )
	:SetPrice( 299 )
	:SetTerm( 30 )
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetDescription( 'Привилегия\nВсе крутые пушки в /kit weapons\nx3 Зарплата и опыт\nДоступны ВСЕ профессии\nДоступен самый лучший Маник\nДоступны все Способности\nДоступна возможность смены Playermodel' )
	:SetOnActivate( function( ePly )
		ePly:SetPrivilege( 'premium', 30 )
		ePly:ChatSend( '~AMBI_PURPLE~ • ~W~ Вы получили Premium на 30 дней' )
	end )
:End()

IGS( 'Premium [Навсегда]', 'priv2_forever' )
	:SetPrice( 699 )
	:SetPerma()
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetDescription( 'Привилегия\nВсе крутые пушки в /kit weapons\nx3 Зарплата и опыт\nДоступны ВСЕ профессии\nДоступен самый лучший Маник\nДоступны все Способности\nДоступна возможность смены Playermodel\nДоступен /kit premium' )
	:SetOnActivate( function( ePly )
		ePly:SetPrivilege( 'premium', 999999 )
		ePly:ChatSend( '~AMBI_PURPLE~ • ~W~ Вы получили Premium навсегда' )
	end )
:End()

-- ------------------------------------------------------------------------------------------------------
local CATEGORY = 'Наборы'

IGS( 'Спец. Оружия', 'kit_dweapons' )
	:SetPrice( 99 )
	:SetTerm( 60 )
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetDescription( 'Работает 60 дней\nЗадержка: 10 минут\nВыдаёт две крутые пушки из VIP и Premium' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Вводите /kit dweapons' )
	end )
:End()

IGS( 'RPG', 'kit_rpg' )
	:SetPrice( 129 )
	:SetTerm( 60 )
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetDescription( 'Работает 60 дней\nЗадержка: 10 минут\nВыдаёт ракетницу Gauss RPG' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Вводите /kit rpg' )
	end )
:End()

IGS( 'Гаусс Пушка', 'kit_gauss' )
	:SetPrice( 199 )
	:SetTerm( 60 )
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetDescription( 'Работает 60 дней\nЗадержка: 20 минут\nВыдаёт ракетницу Gauss Rifle' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Вводите /kit gauss' )
	end )
:End()

IGS( 'Boost +Скорость', 'boost_speed' )
	:SetPrice( 50 )
	:SetTerm( 90 )
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetDescription( 'Работает 90 дней\nЗадержка: 5 минут\nПовышается скорость бега и ходьбу' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Вводите /kit boost1' )
	end )
:End()

IGS( 'Boost +Здоровье', 'boost_hp' )
	:SetPrice( 50 )
	:SetTerm( 90 )
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetDescription( 'Работает 90 дней\nЗадержка: 5 минут\nПовышается здоровье (макс и обычное) на +200' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Вводите /kit boost2' )
	end )
:End()

-- ------------------------------------------------------------------------------------------------------
local CATEGORY = 'Личное'

IGS( 'Работа', 'make_job' )
	:SetPrice( 999 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Требования к покупке профессии:\n1) Проверяете, подходит ли модель под задумку сервера\n2) Согласовываете статистики персонажа с донат-менеджером или Titanovsky.\n3) Оплачиваете заказ' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Обратитесь к Администрации' )
	end )
:End()

IGS( 'PlayerModel', 'make_model' )
	:SetPrice( 899 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Требования к покупке модели:\n1) Проверяете, подходит ли модель под задумку сервера\n2) Согласовываете это с донат-менеджером или Titanovsky.\n3) Оплачиваете заказ' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Обратитесь к Администрации' )
	end )
:End()

IGS( 'Оружие', 'make_swep' )
	:SetPrice( 1000 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Требования к покупке SWEP:\n1) Проверяете, подходит ли SWEP под задумку сервера\n2) Согласовываете это с донат-менеджером или Titanovsky.\n3) Оплачиваете заказ' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Обратитесь к Администрации' )
	end )
:End()

IGS( 'Питомец', 'make_pet' )
	:SetPrice( 1499 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Требования к покупке Личного Питомца:\n1) Проверяете, подходит ли Питомец и его модель под задумку сервера\n2) Согласовываете это с донат-менеджером или Titanovsky.\n3) Оплачиваете заказ' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Обратитесь к Администрации' )
	end )
:End()

IGS( 'Способность', 'make_ability' )
	:SetPrice( 1000 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Требования к покупке способности для вас:\n1) Проверяете, подходит ли способность под задумку сервера\n2) Согласовываете это с донат-менеджером или Titanovsky\n3) Оплачиваете заказ\nДоп услуги к способности:\nУрон - 20 единиц урона за - 100р\nРегенерация с максимальным значением 20.\nОдна единица дополнительной пассивной регенерации - 100р' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Обратитесь к Администрации' )
	end )
:End()

IGS( 'Организация', 'make_org' )
	:SetPrice( 2499 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Требования к покупке Организация:\n1) Проверяете, подходит ли лор, модельки, оружия под задумку сервера\n2) Согласовываете это с донат-менеджером или Titanovsky.\n3) Оплачиваете заказ' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Обратитесь к Администрации' )
	end )
:End()

IGS( 'Здание', 'make_build' )
	:SetPrice( 2999 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Требования к покупке Здания:\n1) Проверяете, подходит ли Здание на карту\n2) Согласовываете это с донат-менеджером или Titanovsky.\n3) Оплачиваете заказ' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Обратитесь к Администрации' )
	end )
:End()

-- ------------------------------------------------------------------------------------------------------
local CATEGORY = 'Питомцы'

IGS( 'НЛО', 'pet_ufo' )
	:SetPrice( 199 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetIcon( 'https://www.freepnglogos.com/uploads/ufo-png/ufo-ufovisitors-ufos-1.png' )
	:SetDescription( 'В инвентарь даётся предмет, не забудьте подготовить всё!\n Питомец следует за хозяином и может давать некоторые баффы' )
	:SetOnActivate( function( ePly )
		ePly:AddInvItemOrDrop( 'pet_ufo', 1 )
	end )
:End()

IGS( 'Меч', 'pet_sword' )
	:SetPrice( 75 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetIcon( 'https://freepngimg.com/thumb/sword/20747-4-transparent-sword-clip-art.png' )
	:SetDescription( 'В инвентарь даётся предмет, не забудьте подготовить всё!\n Питомец следует за хозяином и может давать некоторые баффы' )
	:SetOnActivate( function( ePly )
		ePly:AddInvItemOrDrop( 'pet_sword', 1 )
	end )
:End()

-- ------------------------------------------------------------------------------------------------------
local CATEGORY = 'Perma Оружия'

IGS( 'AK-47', 'perma_ak47' )
	:SetPrice( 99 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetIcon( 'models/weapons/arccw/w_type2.mdl' )
	:SetDescription( 'Бесконечное оружие\nЕсть задержка для взятия в руки (4 минуты)' )
	:SetOnActivate( function( ePly )
		ePly:AddInvItemOrDrop( 'wep_perma_arccw_ak47', 1 )
		ePly:ChatPrint( 'Вам выдалось в инвентарь оружие!' )
	end )
:End()

IGS( 'AWP', 'perma_awp' )
	:SetPrice( 125 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetIcon( 'models/weapons/arccw/w_hs338.mdl' )
	:SetDescription( 'Бесконечное оружие\nЕсть задержка для взятия в руки (4 минуты)' )
	:SetOnActivate( function( ePly )
		ePly:AddInvItemOrDrop( 'wep_perma_arccw_awm', 1 )
		ePly:ChatPrint( 'Вам выдалось в инвентарь оружие!' )
	end )
:End()

IGS( 'Пулемёт 199', 'perma_m14' )
	:SetPrice( 199 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetIcon( 'models/weapons/arccw/w_m14.mdl' )
	:SetDescription( 'Бесконечное оружие\nЕсть задержка для взятия в руки (4 минуты)' )
	:SetOnActivate( function( ePly )
		ePly:AddInvItemOrDrop( 'wep_perma_arccw_m14', 1 )
		ePly:ChatPrint( 'Вам выдалось в инвентарь оружие!' )
	end )
:End()

IGS( 'Desert Eagle', 'perma_deagle' )
	:SetPrice( 199 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetIcon( 'models/weapons/arccw/w_gce.mdl' )
	:SetDescription( 'Бесконечное оружие\nЕсть задержка для взятия в руки (4 минуты)' )
	:SetOnActivate( function( ePly )
		ePly:AddInvItemOrDrop( 'wep_perma_arccw_deagle357', 1 )
		ePly:ChatPrint( 'Вам выдалось в инвентарь оружие!' )
	end )
:End()

IGS( 'Ракетница RPG-7', 'perma_rpg' )
	:SetPrice( 399 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetIcon( 'models/weapons/arccw/w_rpg7.mdl' )
	:SetDescription( 'Бесконечное оружие\nЕсть задержка для взятия в руки (4 минуты)' )
	:SetOnActivate( function( ePly )
		ePly:AddInvItemOrDrop( 'wep_perma_arccw_rpg7', 1 )
		ePly:ChatPrint( 'Вам выдалось в инвентарь оружие!' )
	end )
:End()

IGS( 'Гаусс Пушка', 'perma_gauss' )
	:SetPrice( 799 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetIcon( 'models/weapons/arccw/w_gauss_rifle.mdl' )
	:SetDescription( 'Бесконечное оружие\nЕсть задержка для взятия в руки (4 минуты)\nНе продаётся в обычном магазине!' )
	:SetOnActivate( function( ePly )
		ePly:AddInvItemOrDrop( 'arccw_gauss_rifle', 1 )
		ePly:ChatPrint( 'Вам выдалось в инвентарь оружие!' )
	end )
:End()